services:
  app:
    container_name: your-house-tv
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
        - NEXT_PUBLIC_IMAGEKIT_PRIVATE_KEY=${NEXT_PUBLIC_IMAGEKIT_PRIVATE_KEY}
        - NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY=${NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY}
        - NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT=${NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT}
        - NEXT_PUBLIC_BUNNY_STORAGE_BASE_URL=${NEXT_PUBLIC_BUNNY_STORAGE_BASE_URL}
        - NEXT_PUBLIC_BUNNY_STORAGE_ZONE_NAME=${NEXT_PUBLIC_BUNNY_STORAGE_ZONE_NAME}
        - NEXT_PUBLIC_BUNNY_STORAGE_ACCESS_KEY=${NEXT_PUBLIC_BUNNY_STORAGE_ACCESS_KEY}
        - NEXT_PUBLIC_BUNNY_PULL_ZONE_URL=${NEXT_PUBLIC_BUNNY_PULL_ZONE_URL}
    restart: always
    ports:
      - '3003:3003'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - NEXT_PUBLIC_IMAGEKIT_PRIVATE_KEY=${NEXT_PUBLIC_IMAGEKIT_PRIVATE_KEY}
      - NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY=${NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY}
      - NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT=${NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT}
      - NEXT_PUBLIC_BUNNY_STORAGE_BASE_URL=${NEXT_PUBLIC_BUNNY_STORAGE_BASE_URL}
      - NEXT_PUBLIC_BUNNY_STORAGE_ZONE_NAME=${NEXT_PUBLIC_BUNNY_STORAGE_ZONE_NAME}
      - NEXT_PUBLIC_BUNNY_STORAGE_ACCESS_KEY=${NEXT_PUBLIC_BUNNY_STORAGE_ACCESS_KEY}
      - NEXT_PUBLIC_BUNNY_PULL_ZONE_URL=${NEXT_PUBLIC_BUNNY_PULL_ZONE_URL}
