services:
  app:
    container_name: your-house-tv
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3003:3003'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_IMAGEKIT_PRIVATE_KEY=${NEXT_PUBLIC_IMAGEKIT_PRIVATE_KEY}
      - NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY=${NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY}
      - NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT=${NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT}
    # Add any other required environment variables here
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge
