import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';

const montserrat = Montserrat({
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Your House TV',
  description: 'Generated by Your House TV'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        suppressHydrationWarning
        className={`${montserrat.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
